services:
  emacs:
    restart: always
    build:
      context: .
      dockerfile: ./infra/docker/emacs/Dockerfile
    container_name: 'emacs'
    hostname: 'emacs'
    working_dir: '/opt/org/'
    platform: linux/amd64
    tty: true
    volumes:
      - ./src/.emacs.d:/home/myzn/.emacs.d
      - ./src/tools:/opt/tools
      - ./src/.bashrc:/home/myzn/.bashrc
      - type: bind
        source: ${FOOTPRINTS_DIR}/org
        target: /opt/org
      - type: bind
        source: ${FOOTPRINTS_DIR}/markdown
        target: /opt/markdown

    environment:
      - TZ=Asia/Tokyo
