version: '3.6'
services:
  emacs:
    restart: always
    build:
      context: .
      dockerfile: ./infra/docker/emacs/Dockerfile
    container_name: 'emacs'
    hostname: 'emacs'
    working_dir: '/opt/org/'
    platform: linux/amd64
    tty: true
    volumes:
      - ./src/.emacs.d:/home/myzn/.emacs.d
      - ./src/org:/opt/org
      - ./src/tools:/opt/tools
      - ./src/markdown:/opt/markdown
      - ./src/.bashrc:/home/myzn/.bashrc
    environment:
      - TZ=Asia/Tokyo
