require('nvim-treesitter.configs').setup({
  ensure_installed = { 
    'c',
    'c_sharp',
    'cpp',
    'dart',
    'diff',
    'lua',
    'php',
    'phpdoc',
    'bash',
    'css',
    'comment',
    'commonlisp',
    'dockerfile',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'go',
    'gomod',
    'gowork',
    'gosum',
    'help',
    'html',
    'htmldjango',
    'http',
    'java',
    'javascript',
    'jq',
    'jsdoc',
    'json',
    'json5',
    'jsonnet',
    'jsonc',
    'latex',
    'luap',
    'make',
    'markdown',
    'markdown_inline',
    'python',
    'query',
    'ruby',
    'rust',
    'scss',
    'scala',
    'squirrel',
    'toml',
    'typescript',
    'vim',
    'vue',
    'yaml',
  },
  sync_install = true,
  auto_install = true,
  highlight = {
    enable = true,
    disable = { 'NvimTree' },
    additional_vim_regex_highlighting = true,
  },
  textobjects = {
    select = {
      enable = true,
      lookahead = true,
      keymaps = {
        ["if"] = "@function.inner",
        ["af"] = "@function.outer",
        ["ic"] = "@class.inner",
        ["ac"] = "@class.outer",
        ['ia'] = '@parameter.inner',
        ['aa'] = '@parameter.outer',
      },
    },
  },
  context_commentstring = {
    enable = true,
  },
  indent = {
    enable = true, 
  },
})
