require('nvim-treesitter.configs').setup({
    ensure_installed = { 
      'c',
      'c_sharp',
      'cpp',
      'dart',
      'diff',
      'lua',
      'php',
      'phpdoc',
      'bash',
      'css',
      'comment',
      'commonlisp',
      'dockerfile',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'go',
      'gomod',
      'gowork',
      'gosum',
      'help',
      'html',
      'htmldjango',
      'http',
      'java',
      'javascript',
      'jq',
      'jsdoc',
      'json',
      'json5',
      'jsonnet',
      'jsonc',
      'latex',
      'luap',
      'make',
      'markdown',
      'markdown_inline',
      'python',
      'query',
      'ruby',
      'rust',
      'scss',
      'scala',
      'squirrel',
      'toml',
      'typescript',
      'vim',
      'vue',
      'yaml',
    },
    sync_install = true,
    auto_install = true,
    highlight = {
      enable = true,
    },
    indent = {
      enable = true, 
    },
  })
